name: Issue
description: File an issue.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug!
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the behavior you are seeing and the expected behavior along with steps to reproduce it.
      placeholder: When running a type check with `pyrefly ...`, I expect to see ABC, but get XYZ instead
    validations:
      required: true
  - type: input
    id: sandbox
    attributes:
      label: Sandbox Link
      description: If possible, please provide a reproducible sample of the code you are experiencing the issue in the [Pyrefly Sandbox](https://pyrefly.org/try/).
      placeholder: Pyrefly Sandbox link
    validations:
      required: false
  - type: textarea
    id: ide
    attributes:
      label: (Only applicable for extension issues) IDE Information
      description: Is there anything in the output pane (⇧+⌘+U mac, ctrl+shift+U PC)? Which extension version is installed? Which workspace folders are open in VSCode?
      placeholder: Output shows `panic() ....` on version 0.0.1, mac
    validations:
      required: false
