"""base_types module for synthetic enterprise scale testing.

This file is auto-generated by generate_stress_test.py.

The module intentionally includes:
- Deep inheritance chains.
- Protocol and Generic-heavy APIs.
- Nested Callable, Union, and Mapping type signatures.
- Interconnected imports to form a dense dependency graph.

The purpose is to stress Pyrefly's indexing and type-solving performance.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import (
    Any,
    Callable,
    ClassVar,
    Concatenate,
    cast,
    Generic,
    Mapping,
    MutableMapping,
    ParamSpec,
    Protocol,
    Sequence,
    TypeVar,
    TypeVarTuple,
    Union,
    Unpack,
    runtime_checkable,
)

import tests.perf.scale_test.orchestration as upstream_1
import tests.perf.scale_test.data_layer as downstream_1
import tests.perf.scale_test.domain_models as upstream_2
import tests.perf.scale_test.service_mesh as downstream_2
import tests.perf.scale_test.service_mesh as upstream_3
import tests.perf.scale_test.domain_models as downstream_3
import tests.perf.scale_test.data_layer as upstream_4
import tests.perf.scale_test.orchestration as downstream_4

# Circular import mesh for indexer stress tests.
_MESH_IMPORTS = (upstream_1, downstream_1, upstream_2, downstream_2, upstream_3, downstream_3, upstream_4, downstream_4,)
_MESH_NAMES = tuple(module.__name__.rsplit('.', maxsplit=1)[-1] for module in _MESH_IMPORTS)

T = TypeVar("T")
U = TypeVar("U")
K = TypeVar("K")
V = TypeVar("V")
P = ParamSpec("P")
Ts = TypeVarTuple("Ts")
R = TypeVar("R")
PayloadT = TypeVar("PayloadT", bound="PayloadProtocol")


@runtime_checkable
class PayloadProtocol(Protocol):
    identity: str

    def to_mapping(self) -> Mapping[str, Any]:
        ...


@runtime_checkable
class RepositoryProtocol(Protocol[T]):
    def load(self, key: str) -> T:
        ...

    def save(self, key: str, value: T) -> None:
        ...


class CallableFallback(Generic[K, V]):
    def __init__(self, factory: Callable[[K], V]) -> None:
        self.factory = factory

    def __call__(self, key: K) -> V:
        return self.factory(key)


class GenericEnvelope(Generic[T, U]):
    def __init__(self, payload: T, metadata: U) -> None:
        self.payload = payload
        self.metadata = metadata

    def map_payload(self, mapper: Callable[[T], V]) -> "GenericEnvelope[V, U]":
        return GenericEnvelope(mapper(self.payload), self.metadata)

    def fold(
        self,
        combiner: Callable[[T, U], V],
    ) -> V:
        return combiner(self.payload, self.metadata)

    def apply_callable(
        self,
        fn: Callable[Concatenate[T, P], R],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> R:
        return fn(self.payload, *args, **kwargs)


def _variadic_payload(*items: Unpack[Ts]) -> tuple[Unpack[Ts]]:
    return items


@dataclass
class ModuleDescriptor:
    name: str
    ordinal: int
    upstream: str
    downstream: str


def _chain_transform(
    value: Union[str, int, float],
    steps: Sequence[
        Callable[[Union[str, int, float]], Union[str, int, float]]
    ],
) -> Union[str, int, float]:
    """Apply a chain of transformations to a value.

    Args:
        value: Initial value to be transformed.
        steps: Ordered transformation callables.

    Returns:
        The final transformed value after all functions are applied.
    """
    current: Union[str, int, float] = value
    for step in steps:
        current = step(current)
    return current


class BaseTypesProtocol0(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_0"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode0(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol1(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_1"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode1(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol2(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_2"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode2(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol3(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_3"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode3(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol4(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_4"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode4(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol5(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_5"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode5(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol6(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_6"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode6(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol7(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_7"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode7(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol8(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_8"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode8(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol9(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_9"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode9(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol10(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_10"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode10(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol11(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_11"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode11(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol12(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_12"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode12(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol13(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_13"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode13(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol14(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_14"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode14(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol15(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_15"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode15(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol16(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_16"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode16(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class BaseTypesProtocol17(Protocol[T, U]):
    label: ClassVar[str] = "base_types_protocol_17"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class BaseTypesGenericNode17(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class BaseTypesRoot0(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class BaseTypesChain0Level1(BaseTypesRoot0[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain0Level2(BaseTypesChain0Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain0Level3(BaseTypesChain0Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain0Level4(BaseTypesChain0Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain0Level5(BaseTypesChain0Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain0Level6(BaseTypesChain0Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain0Level7(BaseTypesChain0Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain0Level8(BaseTypesChain0Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesRoot1(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class BaseTypesChain1Level1(BaseTypesRoot1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain1Level2(BaseTypesChain1Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain1Level3(BaseTypesChain1Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain1Level4(BaseTypesChain1Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain1Level5(BaseTypesChain1Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain1Level6(BaseTypesChain1Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain1Level7(BaseTypesChain1Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain1Level8(BaseTypesChain1Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesRoot2(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class BaseTypesChain2Level1(BaseTypesRoot2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain2Level2(BaseTypesChain2Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain2Level3(BaseTypesChain2Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain2Level4(BaseTypesChain2Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain2Level5(BaseTypesChain2Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain2Level6(BaseTypesChain2Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain2Level7(BaseTypesChain2Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain2Level8(BaseTypesChain2Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesRoot3(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class BaseTypesChain3Level1(BaseTypesRoot3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain3Level2(BaseTypesChain3Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain3Level3(BaseTypesChain3Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain3Level4(BaseTypesChain3Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain3Level5(BaseTypesChain3Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain3Level6(BaseTypesChain3Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain3Level7(BaseTypesChain3Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain3Level8(BaseTypesChain3Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesRoot4(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class BaseTypesChain4Level1(BaseTypesRoot4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain4Level2(BaseTypesChain4Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain4Level3(BaseTypesChain4Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain4Level4(BaseTypesChain4Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain4Level5(BaseTypesChain4Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain4Level6(BaseTypesChain4Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain4Level7(BaseTypesChain4Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain4Level8(BaseTypesChain4Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesRoot5(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class BaseTypesChain5Level1(BaseTypesRoot5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain5Level2(BaseTypesChain5Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain5Level3(BaseTypesChain5Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain5Level4(BaseTypesChain5Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain5Level5(BaseTypesChain5Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain5Level6(BaseTypesChain5Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain5Level7(BaseTypesChain5Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain5Level8(BaseTypesChain5Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesRoot6(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class BaseTypesChain6Level1(BaseTypesRoot6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain6Level2(BaseTypesChain6Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain6Level3(BaseTypesChain6Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain6Level4(BaseTypesChain6Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain6Level5(BaseTypesChain6Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain6Level6(BaseTypesChain6Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain6Level7(BaseTypesChain6Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain6Level8(BaseTypesChain6Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesRoot7(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class BaseTypesChain7Level1(BaseTypesRoot7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain7Level2(BaseTypesChain7Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain7Level3(BaseTypesChain7Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain7Level4(BaseTypesChain7Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain7Level5(BaseTypesChain7Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain7Level6(BaseTypesChain7Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain7Level7(BaseTypesChain7Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain7Level8(BaseTypesChain7Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesRoot8(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class BaseTypesChain8Level1(BaseTypesRoot8[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain8Level2(BaseTypesChain8Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain8Level3(BaseTypesChain8Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain8Level4(BaseTypesChain8Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain8Level5(BaseTypesChain8Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain8Level6(BaseTypesChain8Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain8Level7(BaseTypesChain8Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class BaseTypesChain8Level8(BaseTypesChain8Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class BaseTypesService0(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService1(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService2(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService3(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService4(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService5(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService6(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService7(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService8(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService9(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService10(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService11(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService12(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService13(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService14(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService15(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService16(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService17(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService18(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService19(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService20(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class BaseTypesService21(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


def build_base_types_descriptor() -> ModuleDescriptor:
    return ModuleDescriptor(
        name="base_types",
        ordinal=1071,
        upstream="tests.perf.scale_test",
        downstream="tests.perf.scale_test",
    )


def run_base_types_pipeline(
    payload: Union[str, int, float],
    actions: Sequence[
        Callable[[Union[str, int, float]], Union[str, int, float]]
    ],
) -> Union[str, int, float]:
    return _chain_transform(payload, actions)


__all__ = [
    "PayloadProtocol",
    "RepositoryProtocol",
    "GenericEnvelope",
    "ModuleDescriptor",
    "build_base_types_descriptor",
    "run_base_types_pipeline",
]
