"""data_layer module for synthetic enterprise scale testing.

This file is auto-generated by generate_stress_test.py.

The module intentionally includes:
- Deep inheritance chains.
- Protocol and Generic-heavy APIs.
- Nested Callable, Union, and Mapping type signatures.
- Interconnected imports to form a dense dependency graph.

The purpose is to stress Pyrefly's indexing and type-solving performance.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import (
    Any,
    Callable,
    ClassVar,
    Concatenate,
    cast,
    Generic,
    Mapping,
    MutableMapping,
    ParamSpec,
    Protocol,
    Sequence,
    TypeVar,
    TypeVarTuple,
    Union,
    Unpack,
    runtime_checkable,
)

import tests.perf.scale_test.base_types as upstream_1
import tests.perf.scale_test.service_mesh as downstream_1
import tests.perf.scale_test.orchestration as upstream_2
import tests.perf.scale_test.domain_models as downstream_2
import tests.perf.scale_test.domain_models as upstream_3
import tests.perf.scale_test.orchestration as downstream_3
import tests.perf.scale_test.service_mesh as upstream_4
import tests.perf.scale_test.base_types as downstream_4

# Circular import mesh for indexer stress tests.
_MESH_IMPORTS = (
    upstream_1,
    downstream_1,
    upstream_2,
    downstream_2,
    upstream_3,
    downstream_3,
    upstream_4,
    downstream_4,
)
_MESH_NAMES = tuple(module.__name__.rsplit('.', maxsplit=1)
                    [-1] for module in _MESH_IMPORTS)

T = TypeVar("T")
U = TypeVar("U")
K = TypeVar("K")
V = TypeVar("V")
P = ParamSpec("P")
Ts = TypeVarTuple("Ts")
R = TypeVar("R")
PayloadT = TypeVar("PayloadT", bound="PayloadProtocol")


@runtime_checkable
class PayloadProtocol(Protocol):
    identity: str

    def to_mapping(self) -> Mapping[str, Any]:
        ...


@runtime_checkable
class RepositoryProtocol(Protocol[T]):
    def load(self, key: str) -> T:
        ...

    def save(self, key: str, value: T) -> None:
        ...


class CallableFallback(Generic[K, V]):
    def __init__(self, factory: Callable[[K], V]) -> None:
        self.factory = factory

    def __call__(self, key: K) -> V:
        return self.factory(key)


class GenericEnvelope(Generic[T, U]):
    def __init__(self, payload: T, metadata: U) -> None:
        self.payload = payload
        self.metadata = metadata

    def map_payload(self, mapper: Callable[[T], V]) -> "GenericEnvelope[V, U]":
        return GenericEnvelope(mapper(self.payload), self.metadata)

    def fold(
        self,
        combiner: Callable[[T, U], V],
    ) -> V:
        return combiner(self.payload, self.metadata)

    def apply_callable(
        self,
        fn: Callable[Concatenate[T, P], R],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> R:
        return fn(self.payload, *args, **kwargs)


def _variadic_payload(*items: Unpack[Ts]) -> tuple[Unpack[Ts]]:
    return items


@dataclass
class ModuleDescriptor:
    name: str
    ordinal: int
    upstream: str
    downstream: str


def _chain_transform(
    value: Union[str, int, float],
    steps: Sequence[
        Callable[[Union[str, int, float]], Union[str, int, float]]
    ],
) -> Union[str, int, float]:
    """Apply a chain of transformations to a value.

    Args:
        value: Initial value to be transformed.
        steps: Ordered transformation callables.

    Returns:
        The final transformed value after all functions are applied.
    """
    current: Union[str, int, float] = value
    for step in steps:
        current = step(current)
    return current


class DataLayerProtocol0(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_0"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode0(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol1(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_1"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode1(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol2(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_2"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode2(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol3(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_3"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode3(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol4(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_4"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode4(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol5(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_5"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode5(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol6(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_6"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode6(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol7(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_7"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode7(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol8(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_8"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode8(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol9(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_9"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode9(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol10(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_10"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode10(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol11(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_11"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode11(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol12(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_12"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode12(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol13(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_13"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode13(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol14(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_14"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode14(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol15(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_15"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode15(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol16(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_16"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode16(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerProtocol17(Protocol[T, U]):
    label: ClassVar[str] = "data_layer_protocol_17"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DataLayerGenericNode17(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DataLayerRoot0(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload


class DataLayerChain0Level1(DataLayerRoot0[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain0Level2(DataLayerChain0Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain0Level3(DataLayerChain0Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain0Level4(DataLayerChain0Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain0Level5(DataLayerChain0Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain0Level6(DataLayerChain0Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain0Level7(DataLayerChain0Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain0Level8(DataLayerChain0Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerRoot1(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload


class DataLayerChain1Level1(DataLayerRoot1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain1Level2(DataLayerChain1Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain1Level3(DataLayerChain1Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain1Level4(DataLayerChain1Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain1Level5(DataLayerChain1Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain1Level6(DataLayerChain1Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain1Level7(DataLayerChain1Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain1Level8(DataLayerChain1Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerRoot2(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload


class DataLayerChain2Level1(DataLayerRoot2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain2Level2(DataLayerChain2Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain2Level3(DataLayerChain2Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain2Level4(DataLayerChain2Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain2Level5(DataLayerChain2Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain2Level6(DataLayerChain2Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain2Level7(DataLayerChain2Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain2Level8(DataLayerChain2Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerRoot3(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload


class DataLayerChain3Level1(DataLayerRoot3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain3Level2(DataLayerChain3Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain3Level3(DataLayerChain3Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain3Level4(DataLayerChain3Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain3Level5(DataLayerChain3Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain3Level6(DataLayerChain3Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain3Level7(DataLayerChain3Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain3Level8(DataLayerChain3Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerRoot4(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload


class DataLayerChain4Level1(DataLayerRoot4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain4Level2(DataLayerChain4Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain4Level3(DataLayerChain4Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain4Level4(DataLayerChain4Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain4Level5(DataLayerChain4Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain4Level6(DataLayerChain4Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain4Level7(DataLayerChain4Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain4Level8(DataLayerChain4Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerRoot5(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload


class DataLayerChain5Level1(DataLayerRoot5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain5Level2(DataLayerChain5Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain5Level3(DataLayerChain5Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain5Level4(DataLayerChain5Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain5Level5(DataLayerChain5Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain5Level6(DataLayerChain5Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain5Level7(DataLayerChain5Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain5Level8(DataLayerChain5Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerRoot6(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload


class DataLayerChain6Level1(DataLayerRoot6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain6Level2(DataLayerChain6Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain6Level3(DataLayerChain6Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain6Level4(DataLayerChain6Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain6Level5(DataLayerChain6Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain6Level6(DataLayerChain6Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain6Level7(DataLayerChain6Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain6Level8(DataLayerChain6Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerRoot7(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload


class DataLayerChain7Level1(DataLayerRoot7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain7Level2(DataLayerChain7Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain7Level3(DataLayerChain7Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain7Level4(DataLayerChain7Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain7Level5(DataLayerChain7Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain7Level6(DataLayerChain7Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain7Level7(DataLayerChain7Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain7Level8(DataLayerChain7Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerRoot8(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload


class DataLayerChain8Level1(DataLayerRoot8[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain8Level2(DataLayerChain8Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain8Level3(DataLayerChain8Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain8Level4(DataLayerChain8Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain8Level5(DataLayerChain8Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain8Level6(DataLayerChain8Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain8Level7(DataLayerChain8Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerChain8Level8(DataLayerChain8Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DataLayerService0(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService1(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService2(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService3(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService4(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService5(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService6(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService7(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService8(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService9(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService10(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService11(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService12(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService13(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService14(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService15(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService16(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService17(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService18(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService19(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService20(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


class DataLayerService21(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


def build_data_layer_descriptor() -> ModuleDescriptor:
    return ModuleDescriptor(
        name="data_layer",
        ordinal=1046,
        upstream="tests.perf.scale_test",
        downstream="tests.perf.scale_test",
    )


def run_data_layer_pipeline(
    payload: Union[str, int, float],
    actions: Sequence[
        Callable[[Union[str, int, float]], Union[str, int, float]]
    ],
) -> Union[str, int, float]:
    return _chain_transform(payload, actions)


__all__ = [
    "PayloadProtocol",
    "RepositoryProtocol",
    "GenericEnvelope",
    "ModuleDescriptor",
    "build_data_layer_descriptor",
    "run_data_layer_pipeline",
]
