"""domain_models module for synthetic enterprise scale testing.

This file is auto-generated by generate_stress_test.py.

The module intentionally includes:
- Deep inheritance chains.
- Protocol and Generic-heavy APIs.
- Nested Callable, Union, and Mapping type signatures.
- Interconnected imports to form a dense dependency graph.

The purpose is to stress Pyrefly's indexing and type-solving performance.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import (
    Any,
    Callable,
    ClassVar,
    Concatenate,
    cast,
    Generic,
    Mapping,
    MutableMapping,
    ParamSpec,
    Protocol,
    Sequence,
    TypeVar,
    TypeVarTuple,
    Union,
    Unpack,
    runtime_checkable,
)

import tests.perf.scale_test.service_mesh as upstream_1
import tests.perf.scale_test.orchestration as downstream_1
import tests.perf.scale_test.data_layer as upstream_2
import tests.perf.scale_test.base_types as downstream_2
import tests.perf.scale_test.base_types as upstream_3
import tests.perf.scale_test.data_layer as downstream_3
import tests.perf.scale_test.orchestration as upstream_4
import tests.perf.scale_test.service_mesh as downstream_4

# Circular import mesh for indexer stress tests.
_MESH_IMPORTS = (upstream_1, downstream_1, upstream_2, downstream_2, upstream_3, downstream_3, upstream_4, downstream_4,)
_MESH_NAMES = tuple(module.__name__.rsplit('.', maxsplit=1)[-1] for module in _MESH_IMPORTS)

T = TypeVar("T")
U = TypeVar("U")
K = TypeVar("K")
V = TypeVar("V")
P = ParamSpec("P")
Ts = TypeVarTuple("Ts")
R = TypeVar("R")
PayloadT = TypeVar("PayloadT", bound="PayloadProtocol")


@runtime_checkable
class PayloadProtocol(Protocol):
    identity: str

    def to_mapping(self) -> Mapping[str, Any]:
        ...


@runtime_checkable
class RepositoryProtocol(Protocol[T]):
    def load(self, key: str) -> T:
        ...

    def save(self, key: str, value: T) -> None:
        ...


class CallableFallback(Generic[K, V]):
    def __init__(self, factory: Callable[[K], V]) -> None:
        self.factory = factory

    def __call__(self, key: K) -> V:
        return self.factory(key)


class GenericEnvelope(Generic[T, U]):
    def __init__(self, payload: T, metadata: U) -> None:
        self.payload = payload
        self.metadata = metadata

    def map_payload(self, mapper: Callable[[T], V]) -> "GenericEnvelope[V, U]":
        return GenericEnvelope(mapper(self.payload), self.metadata)

    def fold(
        self,
        combiner: Callable[[T, U], V],
    ) -> V:
        return combiner(self.payload, self.metadata)

    def apply_callable(
        self,
        fn: Callable[Concatenate[T, P], R],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> R:
        return fn(self.payload, *args, **kwargs)


def _variadic_payload(*items: Unpack[Ts]) -> tuple[Unpack[Ts]]:
    return items


@dataclass
class ModuleDescriptor:
    name: str
    ordinal: int
    upstream: str
    downstream: str


def _chain_transform(
    value: Union[str, int, float],
    steps: Sequence[
        Callable[[Union[str, int, float]], Union[str, int, float]]
    ],
) -> Union[str, int, float]:
    """Apply a chain of transformations to a value.

    Args:
        value: Initial value to be transformed.
        steps: Ordered transformation callables.

    Returns:
        The final transformed value after all functions are applied.
    """
    current: Union[str, int, float] = value
    for step in steps:
        current = step(current)
    return current


class DomainModelsProtocol0(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_0"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode0(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol1(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_1"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode1(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol2(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_2"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode2(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol3(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_3"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode3(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol4(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_4"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode4(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol5(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_5"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode5(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol6(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_6"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode6(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol7(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_7"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode7(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol8(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_8"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode8(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol9(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_9"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode9(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol10(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_10"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode10(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol11(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_11"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode11(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol12(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_12"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode12(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol13(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_13"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode13(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol14(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_14"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode14(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol15(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_15"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode15(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol16(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_16"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode16(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class DomainModelsProtocol17(Protocol[T, U]):
    label: ClassVar[str] = "domain_models_protocol_17"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class DomainModelsGenericNode17(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class DomainModelsRoot0(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class DomainModelsChain0Level1(DomainModelsRoot0[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain0Level2(DomainModelsChain0Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain0Level3(DomainModelsChain0Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain0Level4(DomainModelsChain0Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain0Level5(DomainModelsChain0Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain0Level6(DomainModelsChain0Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain0Level7(DomainModelsChain0Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain0Level8(DomainModelsChain0Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsRoot1(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class DomainModelsChain1Level1(DomainModelsRoot1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain1Level2(DomainModelsChain1Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain1Level3(DomainModelsChain1Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain1Level4(DomainModelsChain1Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain1Level5(DomainModelsChain1Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain1Level6(DomainModelsChain1Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain1Level7(DomainModelsChain1Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain1Level8(DomainModelsChain1Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsRoot2(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class DomainModelsChain2Level1(DomainModelsRoot2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain2Level2(DomainModelsChain2Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain2Level3(DomainModelsChain2Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain2Level4(DomainModelsChain2Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain2Level5(DomainModelsChain2Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain2Level6(DomainModelsChain2Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain2Level7(DomainModelsChain2Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain2Level8(DomainModelsChain2Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsRoot3(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class DomainModelsChain3Level1(DomainModelsRoot3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain3Level2(DomainModelsChain3Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain3Level3(DomainModelsChain3Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain3Level4(DomainModelsChain3Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain3Level5(DomainModelsChain3Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain3Level6(DomainModelsChain3Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain3Level7(DomainModelsChain3Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain3Level8(DomainModelsChain3Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsRoot4(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class DomainModelsChain4Level1(DomainModelsRoot4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain4Level2(DomainModelsChain4Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain4Level3(DomainModelsChain4Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain4Level4(DomainModelsChain4Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain4Level5(DomainModelsChain4Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain4Level6(DomainModelsChain4Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain4Level7(DomainModelsChain4Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain4Level8(DomainModelsChain4Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsRoot5(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class DomainModelsChain5Level1(DomainModelsRoot5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain5Level2(DomainModelsChain5Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain5Level3(DomainModelsChain5Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain5Level4(DomainModelsChain5Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain5Level5(DomainModelsChain5Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain5Level6(DomainModelsChain5Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain5Level7(DomainModelsChain5Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain5Level8(DomainModelsChain5Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsRoot6(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class DomainModelsChain6Level1(DomainModelsRoot6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain6Level2(DomainModelsChain6Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain6Level3(DomainModelsChain6Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain6Level4(DomainModelsChain6Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain6Level5(DomainModelsChain6Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain6Level6(DomainModelsChain6Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain6Level7(DomainModelsChain6Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain6Level8(DomainModelsChain6Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsRoot7(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class DomainModelsChain7Level1(DomainModelsRoot7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain7Level2(DomainModelsChain7Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain7Level3(DomainModelsChain7Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain7Level4(DomainModelsChain7Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain7Level5(DomainModelsChain7Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain7Level6(DomainModelsChain7Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain7Level7(DomainModelsChain7Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain7Level8(DomainModelsChain7Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsRoot8(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class DomainModelsChain8Level1(DomainModelsRoot8[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain8Level2(DomainModelsChain8Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain8Level3(DomainModelsChain8Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain8Level4(DomainModelsChain8Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain8Level5(DomainModelsChain8Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain8Level6(DomainModelsChain8Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain8Level7(DomainModelsChain8Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class DomainModelsChain8Level8(DomainModelsChain8Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class DomainModelsService0(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService1(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService2(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService3(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService4(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService5(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService6(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService7(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService8(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService9(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService10(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService11(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService12(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService13(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService14(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService15(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService16(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService17(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService18(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService19(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService20(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class DomainModelsService21(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


def build_domain_models_descriptor() -> ModuleDescriptor:
    return ModuleDescriptor(
        name="domain_models",
        ordinal=1371,
        upstream="tests.perf.scale_test",
        downstream="tests.perf.scale_test",
    )


def run_domain_models_pipeline(
    payload: Union[str, int, float],
    actions: Sequence[
        Callable[[Union[str, int, float]], Union[str, int, float]]
    ],
) -> Union[str, int, float]:
    return _chain_transform(payload, actions)


__all__ = [
    "PayloadProtocol",
    "RepositoryProtocol",
    "GenericEnvelope",
    "ModuleDescriptor",
    "build_domain_models_descriptor",
    "run_domain_models_pipeline",
]
