#!/usr/bin/env python3
"""Generate a synthetic enterprise Python codebase for Pyrefly scale testing.

This script creates a large, strongly-typed module graph that is intended
to stress test:

1. Recursive class hierarchy solving in the type engine.
2. Generic and protocol-heavy constraint resolution.
3. Import graph indexing and dependency traversal.
4. Throughput on large file counts and large module sizes.

The generated modules are deterministic and valid Python code.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from textwrap import dedent

DEFAULT_MODULE_COUNT = 120
MIN_LINE_COUNT = 520
CORE_MODULES = [
    "base_types",
    "data_layer",
    "service_mesh",
    "domain_models",
    "orchestration",
]


HEADER_TEMPLATE = '''\
"""{module_name} module for synthetic enterprise scale testing.

This file is auto-generated by generate_stress_test.py.

The module intentionally includes:
- Deep inheritance chains.
- Protocol and Generic-heavy APIs.
- Nested Callable, Union, and Mapping type signatures.
- Interconnected imports to form a dense dependency graph.

The purpose is to stress Pyrefly's indexing and type-solving performance.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import (
    Any,
    Callable,
    ClassVar,
    Concatenate,
    cast,
    Generic,
    Mapping,
    MutableMapping,
    ParamSpec,
    Protocol,
    Sequence,
    TypeVar,
    TypeVarTuple,
    Union,
    Unpack,
    runtime_checkable,
)

{import_block}

T = TypeVar("T")
U = TypeVar("U")
K = TypeVar("K")
V = TypeVar("V")
P = ParamSpec("P")
Ts = TypeVarTuple("Ts")
R = TypeVar("R")
PayloadT = TypeVar("PayloadT", bound="PayloadProtocol")


@runtime_checkable
class PayloadProtocol(Protocol):
    identity: str

    def to_mapping(self) -> Mapping[str, Any]:
        ...


@runtime_checkable
class RepositoryProtocol(Protocol[T]):
    def load(self, key: str) -> T:
        ...

    def save(self, key: str, value: T) -> None:
        ...


class CallableFallback(Generic[K, V]):
    def __init__(self, factory: Callable[[K], V]) -> None:
        self.factory = factory

    def __call__(self, key: K) -> V:
        return self.factory(key)


class GenericEnvelope(Generic[T, U]):
    def __init__(self, payload: T, metadata: U) -> None:
        self.payload = payload
        self.metadata = metadata

    def map_payload(self, mapper: Callable[[T], V]) -> "GenericEnvelope[V, U]":
        return GenericEnvelope(mapper(self.payload), self.metadata)

    def fold(
        self,
        combiner: Callable[[T, U], V],
    ) -> V:
        return combiner(self.payload, self.metadata)

    def apply_callable(
        self,
        fn: Callable[Concatenate[T, P], R],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> R:
        return fn(self.payload, *args, **kwargs)


def _variadic_payload(*items: Unpack[Ts]) -> tuple[Unpack[Ts]]:
    return items


@dataclass
class ModuleDescriptor:
    name: str
    ordinal: int
    upstream: str
    downstream: str


def _chain_transform(
    value: Union[str, int, float],
    steps: Sequence[
        Callable[[Union[str, int, float]], Union[str, int, float]]
    ],
) -> Union[str, int, float]:
    """Apply a chain of transformations to a value.

    Args:
        value: Initial value to be transformed.
        steps: Ordered transformation callables.

    Returns:
        The final transformed value after all functions are applied.
    """
    current: Union[str, int, float] = value
    for step in steps:
        current = step(current)
    return current

'''


def _import_block(
    module_name: str,
    module_names: list[str],
    depth: int = 4,
) -> str:
    """Build interconnected import block for mesh-like dependency traversal."""
    index = module_names.index(module_name)
    imports: list[str] = []
    aliases: list[str] = []
    for offset in range(1, depth + 1):
        prev_name = module_names[(index - offset) % len(module_names)]
        next_name = module_names[(index + offset) % len(module_names)]
        prev_alias = f"upstream_{offset}"
        next_alias = f"downstream_{offset}"
        imports.append(
            f"import tests.perf.scale_test.{prev_name} as {prev_alias}")
        imports.append(
            f"import tests.perf.scale_test.{next_name} as {next_alias}")
        aliases.extend([prev_alias, next_alias])
    if imports:
        imports.append("")
        imports.append("# Circular import mesh for indexer stress tests.")
        imports.append("_MESH_IMPORTS = (" + ", ".join(aliases) + ",)")
        imports.append(
            "_MESH_NAMES = tuple(module.__name__.rsplit('.', maxsplit=1)[-1] "
            "for module in _MESH_IMPORTS)"
        )
        return "\n".join(imports)
    return ""


def _protocol_section(module_name: str, section_size: int) -> str:
    """Generate protocol and generic abstraction section."""
    lines: list[str] = []
    root_name = module_name.title().replace("_", "")
    for i in range(section_size):
        lines.append(
            dedent(
                f'''
                class {root_name}Protocol{i}(Protocol[T, U]):
                    label: ClassVar[str] = "{module_name}_protocol_{i}"

                    def evaluate(
                        self,
                        payload: T,
                        metadata: U,
                        callback: Callable[[Union[T, U]], Union[T, U]],
                    ) -> Union[T, U]:
                        ...

                    def evaluate_variadic(
                        self,
                        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
                        *items: Unpack[Ts],
                    ) -> Union[T, U]:
                        ...


                class {root_name}GenericNode{i}(Generic[T, U]):
                    def __init__(
                        self,
                        key: str,
                        value: T,
                        metadata: U,
                    ) -> None:
                        self.key = key
                        self.value = value
                        self.metadata = metadata

                    def pipeline(
                        self,
                        stages: Sequence[
                            Callable[[Union[T, U]], Union[T, U]]
                        ],
                    ) -> Union[T, U]:
                        state: Union[T, U] = self.value
                        for stage in stages:
                            state = stage(state)
                        return state

                    def variadic_pipeline(
                        self,
                        callback: Callable[Concatenate[T, P], U],
                        *args: P.args,
                        **kwargs: P.kwargs,
                    ) -> U:
                        return callback(self.value, *args, **kwargs)
                '''
            ).strip()
        )
    return "\n\n".join(lines)


def _inheritance_section(
    module_name: str,
    chain_count: int,
    depth: int = 8,
) -> str:
    """Generate deep inheritance chains between 5 and 10 levels."""
    lines: list[str] = []
    root = module_name.title().replace("_", "")
    for chain in range(chain_count):
        previous = f"{root}Root{chain}"
        lines.append(
            dedent(
                f'''
                class {previous}(Generic[T]):
                    def __init__(self, payload: T) -> None:
                        self.payload = payload

                    def project(self) -> T:
                        return self.payload
                '''
            ).strip()
        )
        for level in range(1, depth + 1):
            current = f"{root}Chain{chain}Level{level}"
            lines.append(
                dedent(
                    f'''
                    class {current}({previous}[T]):
                        def project(self) -> T:
                            candidate = super().project()
                            return candidate
                    '''
                ).strip()
            )
            previous = current
    return "\n\n".join(lines)


def _services_section(module_name: str, section_size: int) -> str:
    """Generate typed service interfaces and implementations."""
    lines: list[str] = []
    root = module_name.title().replace("_", "")
    for i in range(section_size):
        lines.append(
            dedent(
                f'''
                class {root}Service{i}(Generic[K, V]):
                    def __init__(self, storage: MutableMapping[K, V]) -> None:
                        self.storage = storage

                    def transact(
                        self,
                        key: K,
                        fallback: Union[V, CallableFallback[K, V]],
                        mutator: Callable[[Union[V, K]], Union[V, K]],
                    ) -> V:
                        if key in self.storage:
                            current: Union[V, K] = self.storage[key]
                        elif isinstance(fallback, CallableFallback):
                            current = fallback(key)
                        else:
                            current = fallback
                        next_value = mutator(current)
                        if isinstance(next_value, type(key)):
                            raise TypeError(
                                "Mutator returned key-like value"
                            )
                        resolved_value = cast(V, next_value)
                        self.storage[key] = resolved_value
                        return resolved_value

                    def compose(
                        self,
                        operators: Sequence[
                            Callable[[Mapping[K, V]], Mapping[K, V]]
                        ],
                    ) -> Mapping[K, V]:
                        result: Mapping[K, V] = dict(self.storage)
                        for operator in operators:
                            result = operator(result)
                        return result

                    def run_with_context(
                        self,
                        key: K,
                        callback: Callable[Concatenate[K, P], V],
                        *args: P.args,
                        **kwargs: P.kwargs,
                    ) -> V:
                        value = callback(key, *args, **kwargs)
                        self.storage[key] = value
                        return value

                    def vectorize(
                        self,
                        *items: Unpack[Ts],
                    ) -> tuple[Unpack[Ts]]:
                        return items
                '''
            ).strip()
        )
    return "\n\n".join(lines)


def _entrypoint_section(module_name: str) -> str:
    """Generate deterministic public API entry points for each module."""
    ordinal = sum(ord(ch) for ch in module_name) % 10000
    return dedent(
        f'''
        def build_{module_name}_descriptor() -> ModuleDescriptor:
            return ModuleDescriptor(
                name="{module_name}",
                ordinal={ordinal},
                upstream="tests.perf.scale_test",
                downstream="tests.perf.scale_test",
            )


        def run_{module_name}_pipeline(
            payload: Union[str, int, float],
            actions: Sequence[
                Callable[[Union[str, int, float]], Union[str, int, float]]
            ],
        ) -> Union[str, int, float]:
            return _chain_transform(payload, actions)


        __all__ = [
            "PayloadProtocol",
            "RepositoryProtocol",
            "CallableFallback",
            "GenericEnvelope",
            "ModuleDescriptor",
            "build_{module_name}_descriptor",
            "run_{module_name}_pipeline",
        ]
        '''
    ).strip()


def _render_module(
    module_name: str,
    module_names: list[str],
    min_lines: int,
) -> str:
    """Render a module and pad it to the minimum target line count."""
    sections: list[str] = []
    sections.append(
        HEADER_TEMPLATE.format(
            module_name=module_name,
            import_block=_import_block(module_name, module_names),
        ).strip()
    )
    sections.append(_protocol_section(module_name, section_size=18))
    sections.append(_inheritance_section(module_name, chain_count=9, depth=8))
    sections.append(_services_section(module_name, section_size=22))
    sections.append(_entrypoint_section(module_name))

    module_body = "\n\n\n".join(sections).strip() + "\n"
    lines = module_body.splitlines()

    if len(lines) < min_lines:
        filler_index = 0
        while len(lines) < min_lines:
            lines.extend(
                [
                    "",
                    f"def _filler_symbol_{filler_index}(value: int) -> int:",
                    '    """Filler function for deterministic file size."""',
                    f"    return value + {filler_index}",
                ]
            )
            filler_index += 1

    return "\n".join(lines) + "\n"


def _build_module_names(module_count: int) -> list[str]:
    """Construct module names with core modules first."""
    if module_count < len(CORE_MODULES):
        raise ValueError(
            "module_count must be >= "
            f"{len(CORE_MODULES)} to include core modules"
        )
    names = list(CORE_MODULES)
    for i in range(module_count - len(CORE_MODULES)):
        names.append(f"generated_module_{i:03d}")
    return names


def generate_modules(
    output_dir: Path,
    module_count: int,
    min_lines: int,
    core_only: bool,
) -> list[Path]:
    """Generate synthetic enterprise modules in the output directory.

    Args:
        output_dir: Destination directory for generated modules.
        module_count: Number of modules to generate.
        min_lines: Minimum line count for each generated module.
        core_only: When true, emit only the first five core modules.

    Returns:
        Paths to generated module files.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    module_names = _build_module_names(module_count)
    selected_names = CORE_MODULES if core_only else module_names
    dependency_names = selected_names if core_only else module_names

    written: list[Path] = []
    for module_name in selected_names:
        destination = output_dir / f"{module_name}.py"
        destination.write_text(
            _render_module(module_name, dependency_names, min_lines=min_lines),
            encoding="utf-8",
        )
        written.append(destination)

    init_file = output_dir / "__init__.py"
    exports = "\n".join(f"from . import {name}" for name in selected_names)
    all_exports = ",\n    ".join(f'"{name}"' for name in selected_names)
    init_file.write_text(
        (
            '"""Synthetic enterprise stress-test package for Pyrefly."""\n\n'
            + exports
            + "\n\n"
            + "__all__ = [\n    "
            + all_exports
            + "\n]\n"
        ),
        encoding="utf-8",
    )

    return written


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Generate synthetic enterprise stress-test Python modules."
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("tests/perf/scale_test"),
        help="Directory where modules are generated.",
    )
    parser.add_argument(
        "--module-count",
        type=int,
        default=DEFAULT_MODULE_COUNT,
        help="Total number of modules to generate.",
    )
    parser.add_argument(
        "--min-lines",
        type=int,
        default=MIN_LINE_COUNT,
        help="Minimum line count per generated file.",
    )
    parser.add_argument(
        "--core-only",
        action="store_true",
        help="Generate only the five core modules.",
    )
    return parser.parse_args()


def main() -> None:
    """Generate modules and print a concise summary."""
    args = parse_args()
    written = generate_modules(
        output_dir=args.output_dir,
        module_count=args.module_count,
        min_lines=args.min_lines,
        core_only=args.core_only,
    )
    print(
        f"Generated {len(written)} module(s) in {args.output_dir} "
        f"with minimum {args.min_lines} lines each."
    )


if __name__ == "__main__":
    main()
