"""service_mesh module for synthetic enterprise scale testing.

This file is auto-generated by generate_stress_test.py.

The module intentionally includes:
- Deep inheritance chains.
- Protocol and Generic-heavy APIs.
- Nested Callable, Union, and Mapping type signatures.
- Interconnected imports to form a dense dependency graph.

The purpose is to stress Pyrefly's indexing and type-solving performance.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import (
    Any,
    Callable,
    ClassVar,
    Concatenate,
    cast,
    Generic,
    Mapping,
    MutableMapping,
    ParamSpec,
    Protocol,
    Sequence,
    TypeVar,
    TypeVarTuple,
    Union,
    Unpack,
    runtime_checkable,
)

import tests.perf.scale_test.data_layer as upstream_1
import tests.perf.scale_test.domain_models as downstream_1
import tests.perf.scale_test.base_types as upstream_2
import tests.perf.scale_test.orchestration as downstream_2
import tests.perf.scale_test.orchestration as upstream_3
import tests.perf.scale_test.base_types as downstream_3
import tests.perf.scale_test.domain_models as upstream_4
import tests.perf.scale_test.data_layer as downstream_4

# Circular import mesh for indexer stress tests.
_MESH_IMPORTS = (upstream_1, downstream_1, upstream_2, downstream_2, upstream_3, downstream_3, upstream_4, downstream_4,)
_MESH_NAMES = tuple(module.__name__.rsplit('.', maxsplit=1)[-1] for module in _MESH_IMPORTS)

T = TypeVar("T")
U = TypeVar("U")
K = TypeVar("K")
V = TypeVar("V")
P = ParamSpec("P")
Ts = TypeVarTuple("Ts")
R = TypeVar("R")
PayloadT = TypeVar("PayloadT", bound="PayloadProtocol")


@runtime_checkable
class PayloadProtocol(Protocol):
    identity: str

    def to_mapping(self) -> Mapping[str, Any]:
        ...


@runtime_checkable
class RepositoryProtocol(Protocol[T]):
    def load(self, key: str) -> T:
        ...

    def save(self, key: str, value: T) -> None:
        ...


class CallableFallback(Generic[K, V]):
    def __init__(self, factory: Callable[[K], V]) -> None:
        self.factory = factory

    def __call__(self, key: K) -> V:
        return self.factory(key)


class GenericEnvelope(Generic[T, U]):
    def __init__(self, payload: T, metadata: U) -> None:
        self.payload = payload
        self.metadata = metadata

    def map_payload(self, mapper: Callable[[T], V]) -> "GenericEnvelope[V, U]":
        return GenericEnvelope(mapper(self.payload), self.metadata)

    def fold(
        self,
        combiner: Callable[[T, U], V],
    ) -> V:
        return combiner(self.payload, self.metadata)

    def apply_callable(
        self,
        fn: Callable[Concatenate[T, P], R],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> R:
        return fn(self.payload, *args, **kwargs)


def _variadic_payload(*items: Unpack[Ts]) -> tuple[Unpack[Ts]]:
    return items


@dataclass
class ModuleDescriptor:
    name: str
    ordinal: int
    upstream: str
    downstream: str


def _chain_transform(
    value: Union[str, int, float],
    steps: Sequence[
        Callable[[Union[str, int, float]], Union[str, int, float]]
    ],
) -> Union[str, int, float]:
    """Apply a chain of transformations to a value.

    Args:
        value: Initial value to be transformed.
        steps: Ordered transformation callables.

    Returns:
        The final transformed value after all functions are applied.
    """
    current: Union[str, int, float] = value
    for step in steps:
        current = step(current)
    return current


class ServiceMeshProtocol0(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_0"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode0(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol1(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_1"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode1(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol2(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_2"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode2(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol3(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_3"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode3(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol4(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_4"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode4(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol5(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_5"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode5(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol6(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_6"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode6(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol7(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_7"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode7(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol8(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_8"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode8(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol9(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_9"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode9(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol10(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_10"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode10(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol11(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_11"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode11(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol12(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_12"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode12(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol13(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_13"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode13(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol14(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_14"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode14(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol15(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_15"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode15(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol16(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_16"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode16(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)

class ServiceMeshProtocol17(Protocol[T, U]):
    label: ClassVar[str] = "service_mesh_protocol_17"

    def evaluate(
        self,
        payload: T,
        metadata: U,
        callback: Callable[[Union[T, U]], Union[T, U]],
    ) -> Union[T, U]:
        ...

    def evaluate_variadic(
        self,
        callback: Callable[[tuple[Unpack[Ts]]], Union[T, U]],
        *items: Unpack[Ts],
    ) -> Union[T, U]:
        ...


class ServiceMeshGenericNode17(Generic[T, U]):
    def __init__(
        self,
        key: str,
        value: T,
        metadata: U,
    ) -> None:
        self.key = key
        self.value = value
        self.metadata = metadata

    def pipeline(
        self,
        stages: Sequence[
            Callable[[Union[T, U]], Union[T, U]]
        ],
    ) -> Union[T, U]:
        state: Union[T, U] = self.value
        for stage in stages:
            state = stage(state)
        return state

    def variadic_pipeline(
        self,
        callback: Callable[Concatenate[T, P], U],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> U:
        return callback(self.value, *args, **kwargs)


class ServiceMeshRoot0(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class ServiceMeshChain0Level1(ServiceMeshRoot0[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain0Level2(ServiceMeshChain0Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain0Level3(ServiceMeshChain0Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain0Level4(ServiceMeshChain0Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain0Level5(ServiceMeshChain0Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain0Level6(ServiceMeshChain0Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain0Level7(ServiceMeshChain0Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain0Level8(ServiceMeshChain0Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshRoot1(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class ServiceMeshChain1Level1(ServiceMeshRoot1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain1Level2(ServiceMeshChain1Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain1Level3(ServiceMeshChain1Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain1Level4(ServiceMeshChain1Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain1Level5(ServiceMeshChain1Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain1Level6(ServiceMeshChain1Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain1Level7(ServiceMeshChain1Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain1Level8(ServiceMeshChain1Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshRoot2(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class ServiceMeshChain2Level1(ServiceMeshRoot2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain2Level2(ServiceMeshChain2Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain2Level3(ServiceMeshChain2Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain2Level4(ServiceMeshChain2Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain2Level5(ServiceMeshChain2Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain2Level6(ServiceMeshChain2Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain2Level7(ServiceMeshChain2Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain2Level8(ServiceMeshChain2Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshRoot3(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class ServiceMeshChain3Level1(ServiceMeshRoot3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain3Level2(ServiceMeshChain3Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain3Level3(ServiceMeshChain3Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain3Level4(ServiceMeshChain3Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain3Level5(ServiceMeshChain3Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain3Level6(ServiceMeshChain3Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain3Level7(ServiceMeshChain3Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain3Level8(ServiceMeshChain3Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshRoot4(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class ServiceMeshChain4Level1(ServiceMeshRoot4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain4Level2(ServiceMeshChain4Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain4Level3(ServiceMeshChain4Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain4Level4(ServiceMeshChain4Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain4Level5(ServiceMeshChain4Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain4Level6(ServiceMeshChain4Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain4Level7(ServiceMeshChain4Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain4Level8(ServiceMeshChain4Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshRoot5(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class ServiceMeshChain5Level1(ServiceMeshRoot5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain5Level2(ServiceMeshChain5Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain5Level3(ServiceMeshChain5Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain5Level4(ServiceMeshChain5Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain5Level5(ServiceMeshChain5Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain5Level6(ServiceMeshChain5Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain5Level7(ServiceMeshChain5Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain5Level8(ServiceMeshChain5Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshRoot6(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class ServiceMeshChain6Level1(ServiceMeshRoot6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain6Level2(ServiceMeshChain6Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain6Level3(ServiceMeshChain6Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain6Level4(ServiceMeshChain6Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain6Level5(ServiceMeshChain6Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain6Level6(ServiceMeshChain6Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain6Level7(ServiceMeshChain6Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain6Level8(ServiceMeshChain6Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshRoot7(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class ServiceMeshChain7Level1(ServiceMeshRoot7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain7Level2(ServiceMeshChain7Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain7Level3(ServiceMeshChain7Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain7Level4(ServiceMeshChain7Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain7Level5(ServiceMeshChain7Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain7Level6(ServiceMeshChain7Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain7Level7(ServiceMeshChain7Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain7Level8(ServiceMeshChain7Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshRoot8(Generic[T]):
    def __init__(self, payload: T) -> None:
        self.payload = payload

    def project(self) -> T:
        return self.payload

class ServiceMeshChain8Level1(ServiceMeshRoot8[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain8Level2(ServiceMeshChain8Level1[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain8Level3(ServiceMeshChain8Level2[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain8Level4(ServiceMeshChain8Level3[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain8Level5(ServiceMeshChain8Level4[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain8Level6(ServiceMeshChain8Level5[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain8Level7(ServiceMeshChain8Level6[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate

class ServiceMeshChain8Level8(ServiceMeshChain8Level7[T]):
    def project(self) -> T:
        candidate = super().project()
        return candidate


class ServiceMeshService0(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService1(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService2(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService3(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService4(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService5(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService6(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService7(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService8(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService9(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService10(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService11(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService12(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService13(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService14(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService15(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService16(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService17(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService18(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService19(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService20(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items

class ServiceMeshService21(Generic[K, V]):
    def __init__(self, storage: MutableMapping[K, V]) -> None:
        self.storage = storage

    def transact(
        self,
        key: K,
        fallback: Union[V, CallableFallback[K, V]],
        mutator: Callable[[Union[V, K]], Union[V, K]],
    ) -> V:
        if key in self.storage:
            current: Union[V, K] = self.storage[key]
        elif isinstance(fallback, CallableFallback):
            current = fallback(key)
        else:
            current = fallback
        next_value = mutator(current)
        if isinstance(next_value, type(key)):
            raise TypeError(
                "Mutator returned key-like value"
            )
        resolved_value = cast(V, next_value)
        self.storage[key] = resolved_value
        return resolved_value

    def compose(
        self,
        operators: Sequence[
            Callable[[Mapping[K, V]], Mapping[K, V]]
        ],
    ) -> Mapping[K, V]:
        result: Mapping[K, V] = dict(self.storage)
        for operator in operators:
            result = operator(result)
        return result

    def run_with_context(
        self,
        key: K,
        callback: Callable[Concatenate[K, P], V],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> V:
        value = callback(key, *args, **kwargs)
        self.storage[key] = value
        return value

    def vectorize(
        self,
        *items: Unpack[Ts],
    ) -> tuple[Unpack[Ts]]:
        return items


def build_service_mesh_descriptor() -> ModuleDescriptor:
    return ModuleDescriptor(
        name="service_mesh",
        ordinal=1277,
        upstream="tests.perf.scale_test",
        downstream="tests.perf.scale_test",
    )


def run_service_mesh_pipeline(
    payload: Union[str, int, float],
    actions: Sequence[
        Callable[[Union[str, int, float]], Union[str, int, float]]
    ],
) -> Union[str, int, float]:
    return _chain_transform(payload, actions)


__all__ = [
    "PayloadProtocol",
    "RepositoryProtocol",
    "CallableFallback",
    "GenericEnvelope",
    "ModuleDescriptor",
    "build_service_mesh_descriptor",
    "run_service_mesh_pipeline",
]
