[env]
ERROR_KINDS_DOC_PATH = { value = "website/docs/error-kinds.mdx", relative = true }
TEST_FILES_PATH = { value = "pyrefly/lib/test/lsp/lsp_interaction/test_files", relative = true }
PYDANTIC_TEST_PATH = { value = "pyrefly/lib/test/pydantic/third-party", relative = true }
DJANGO_TEST_PATH = { value = "pyrefly/lib/test/django/third-party", relative = true }
GLEAN_SNAPSHOTS_PATH = { value = "pyrefly/lib/report/glean/snapshots", relative = true }
