# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from collections.abc import Callable
from typing import Any

class Flag[T]: ...
class Int[T]: ...
class IntTuple: ...
class IntVar: ...

def type_shape_dsl_function[F: Callable[..., Any]](fn: F) -> F: ...
