# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from typing import Any, overload, Sequence

from jax._array import Array as _Array, ArrayLike as _ArrayLike
from shape_extensions import broadcast, IntTuple

type _Shape = IntTuple

# Every activation JAX exposes here is elementwise, so the shape is preserved.
# `softmax` and `log_softmax` normalize along `axis` but do not reduce it away.
# `elu` and `leaky_relu` take their parameter as an array as well as a scalar,
# and an array parameter broadcasts against the input rather than preserving
# its shape.
def relu[Shape: _Shape = []](x: _ArrayLike[Shape]) -> _Array[Shape]: ...
def relu6[Shape: _Shape = []](x: _ArrayLike[Shape]) -> _Array[Shape]: ...
def sigmoid[Shape: _Shape = []](x: _ArrayLike[Shape]) -> _Array[Shape]: ...
def softplus[Shape: _Shape = []](x: _ArrayLike[Shape]) -> _Array[Shape]: ...
def soft_sign[Shape: _Shape = []](x: _ArrayLike[Shape]) -> _Array[Shape]: ...
def silu[Shape: _Shape = []](x: _ArrayLike[Shape]) -> _Array[Shape]: ...
def swish[Shape: _Shape = []](x: _ArrayLike[Shape]) -> _Array[Shape]: ...
@overload
def elu[Shape: _Shape = []](
    x: _ArrayLike[Shape], alpha: float = ...
) -> _Array[Shape]: ...
@overload
def elu[Shape: _Shape = [], ParamShape: _Shape = []](
    x: _ArrayLike[Shape], alpha: _ArrayLike[ParamShape] = ...
) -> _Array[broadcast(Shape, ParamShape)]: ...
@overload
def leaky_relu[Shape: _Shape = []](
    x: _ArrayLike[Shape], negative_slope: float = ...
) -> _Array[Shape]: ...
@overload
def leaky_relu[Shape: _Shape = [], ParamShape: _Shape = []](
    x: _ArrayLike[Shape], negative_slope: _ArrayLike[ParamShape] = ...
) -> _Array[broadcast(Shape, ParamShape)]: ...
def gelu[Shape: _Shape = []](
    x: _ArrayLike[Shape], approximate: bool = ...
) -> _Array[Shape]: ...
def hard_tanh[Shape: _Shape = []](x: _ArrayLike[Shape]) -> _Array[Shape]: ...
def softmax[Shape: _Shape = []](
    x: _ArrayLike[Shape], axis: Sequence[int] | int | None = ..., where: Any = ...
) -> _Array[Shape]: ...
def log_softmax[Shape: _Shape = []](
    x: _ArrayLike[Shape], axis: Sequence[int] | int | None = ..., where: Any = ...
) -> _Array[Shape]: ...
