/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

use crate::testcase;

// At some point in the past, this test took many minutes and consumed 50Gb of RAM.
testcase!(
    test_quadratic,
    r#"
from typing import TypeVar
_T = TypeVar("_T")
def table() -> _T: ...
class Configs:
    def __init__(self):
        self.value = {
            "1": {
                "a": table(),
                "b": table(),
                "c": table(),
                "d": table(),
                "e": table(),
                "f": table(),
                "g": table(),
                "h": table(),
                "i": table(),
                "j": table(),
            },
            "2": {
                "a": table(),
                "b": table(),
                "c": table(),
                "d": table(),
                "e": table(),
                "f": table(),
                "g": table(),
                "h": table(),
                "i": table(),
            },
            "3": {},
        }
"#,
);

// Repro for issue #2595: Protocol-vs-Protocol structural subtyping cycle.
testcase!(
    test_protocol_cycle_exponential,
    r#"
from typing import Protocol

class Array1(Protocol):
    def op_0(self, other: "Array1 | complex", /) -> "Array2": ...
    def op_1(self, other: "Array1 | complex", /) -> "Array2": ...
    def op_2(self, other: "Array1 | complex", /) -> "Array2": ...
    def op_3(self, other: "Array1 | complex", /) -> "Array2": ...
    def op_4(self, other: "Array1 | complex", /) -> "Array2": ...
    def op_5(self, other: "Array1 | complex", /) -> "Array2": ...
    def op_6(self, other: "Array1 | complex", /) -> "Array2": ...
    def op_7(self, other: "Array1 | complex", /) -> "Array2": ...
    def op_8(self, other: "Array1 | complex", /) -> "Array2": ...
    def op_9(self, other: "Array1 | complex", /) -> "Array2": ...

class Array2(Protocol):
    def op_0(self, other: "Array2 | complex", /) -> "Array3": ...
    def op_1(self, other: "Array2 | complex", /) -> "Array3": ...
    def op_2(self, other: "Array2 | complex", /) -> "Array3": ...
    def op_3(self, other: "Array2 | complex", /) -> "Array3": ...
    def op_4(self, other: "Array2 | complex", /) -> "Array3": ...
    def op_5(self, other: "Array2 | complex", /) -> "Array3": ...
    def op_6(self, other: "Array2 | complex", /) -> "Array3": ...
    def op_7(self, other: "Array2 | complex", /) -> "Array3": ...
    def op_8(self, other: "Array2 | complex", /) -> "Array3": ...
    def op_9(self, other: "Array2 | complex", /) -> "Array3": ...

class Array3(Protocol):
    def op_0(self, other: "Array3 | complex", /) -> "Array1": ...
    def op_1(self, other: "Array3 | complex", /) -> "Array1": ...
    def op_2(self, other: "Array3 | complex", /) -> "Array1": ...
    def op_3(self, other: "Array3 | complex", /) -> "Array1": ...
    def op_4(self, other: "Array3 | complex", /) -> "Array1": ...
    def op_5(self, other: "Array3 | complex", /) -> "Array1": ...
    def op_6(self, other: "Array3 | complex", /) -> "Array1": ...
    def op_7(self, other: "Array3 | complex", /) -> "Array1": ...
    def op_8(self, other: "Array3 | complex", /) -> "Array1": ...
    def op_9(self, other: "Array3 | complex", /) -> "Array1": ...

class Impl:
    def op_0(self, other: object, /) -> "Impl": ...
    def op_1(self, other: object, /) -> "Impl": ...
    def op_2(self, other: object, /) -> "Impl": ...
    def op_3(self, other: object, /) -> "Impl": ...
    def op_4(self, other: object, /) -> "Impl": ...
    def op_5(self, other: object, /) -> "Impl": ...
    def op_6(self, other: object, /) -> "Impl": ...
    def op_7(self, other: object, /) -> "Impl": ...
    def op_8(self, other: object, /) -> "Impl": ...
    def op_9(self, other: object, /) -> "Impl": ...

def f1(x: Array1 | complex) -> Array1: ...
def f2(x: Array2 | complex) -> Array2: ...
def f3(x: Array3 | complex) -> Array3: ...

def test() -> None:
    val = Impl()
    a1 = f1(val)
    a2 = f2(val)
    a3 = f3(val)
    c1 = f1(a2)
    c2 = f2(a3)
    c3 = f3(a1)
"#,
);
