# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from typing import Any, overload

from jax._array import Array
from jax._shapes import lax_broadcast
from shape_extensions import IntTuple

from . import linalg as linalg

type _Shape = IntTuple
type _Scalar = int | float | complex

# Unary elementwise operators
def abs[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def acos[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def acosh[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def asin[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def asinh[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def atan[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def atanh[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def bessel_i0e[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def bessel_i1e[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def bitwise_not[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def cbrt[Shape: _Shape](x: Array[Shape], *, accuracy: Any = None) -> Array[Shape]: ...
def ceil[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def clz[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def conj[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def cos[Shape: _Shape](x: Array[Shape], *, accuracy: Any = None) -> Array[Shape]: ...
def cosh[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def digamma[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def erf[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def erf_inv[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def erfc[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def exp[Shape: _Shape](x: Array[Shape], *, accuracy: Any = None) -> Array[Shape]: ...
def exp2[Shape: _Shape](x: Array[Shape], *, accuracy: Any = None) -> Array[Shape]: ...
def expm1[Shape: _Shape](x: Array[Shape], *, accuracy: Any = None) -> Array[Shape]: ...
def floor[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def imag[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def integer_pow[Shape: _Shape](x: Array[Shape], y: int) -> Array[Shape]: ...
def is_finite[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def lgamma[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def log[Shape: _Shape](x: Array[Shape], *, accuracy: Any = None) -> Array[Shape]: ...
def log1p[Shape: _Shape](x: Array[Shape], *, accuracy: Any = None) -> Array[Shape]: ...
def logistic[Shape: _Shape](
    x: Array[Shape], *, accuracy: Any = None
) -> Array[Shape]: ...
def neg[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def population_count[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def real[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def reciprocal[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def round[Shape: _Shape](
    x: Array[Shape], rounding_method: Any = ...
) -> Array[Shape]: ...
def rsqrt[Shape: _Shape](x: Array[Shape], *, accuracy: Any = None) -> Array[Shape]: ...
def sign[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def sin[Shape: _Shape](x: Array[Shape], *, accuracy: Any = None) -> Array[Shape]: ...
def sinh[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def sqrt[Shape: _Shape](x: Array[Shape], *, accuracy: Any = None) -> Array[Shape]: ...
def square[Shape: _Shape](x: Array[Shape]) -> Array[Shape]: ...
def tan[Shape: _Shape](x: Array[Shape], *, accuracy: Any = None) -> Array[Shape]: ...
def tanh[Shape: _Shape](x: Array[Shape], *, accuracy: Any = None) -> Array[Shape]: ...

# Binary elementwise operators with strict rank-matching broadcasting
@overload
def add[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def add[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def add[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def atan2[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def atan2[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def atan2[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def bitwise_and[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def bitwise_and[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def bitwise_and[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def bitwise_or[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def bitwise_or[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def bitwise_or[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def bitwise_xor[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def bitwise_xor[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def bitwise_xor[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def complex[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def complex[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def complex[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def div[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def div[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def div[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def eq[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def eq[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def eq[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def ge[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def ge[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def ge[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def gt[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def gt[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def gt[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def igamma[Shape: _Shape](a: Array[Shape], x: _Scalar, /) -> Array[Shape]: ...
@overload
def igamma[Shape: _Shape](a: _Scalar, x: Array[Shape], /) -> Array[Shape]: ...
@overload
def igamma[Shape1: _Shape, Shape2: _Shape](
    a: Array[Shape1], x: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def igamma_grad_a[Shape: _Shape](a: Array[Shape], x: _Scalar, /) -> Array[Shape]: ...
@overload
def igamma_grad_a[Shape: _Shape](a: _Scalar, x: Array[Shape], /) -> Array[Shape]: ...
@overload
def igamma_grad_a[Shape1: _Shape, Shape2: _Shape](
    a: Array[Shape1], x: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def igammac[Shape: _Shape](a: Array[Shape], x: _Scalar, /) -> Array[Shape]: ...
@overload
def igammac[Shape: _Shape](a: _Scalar, x: Array[Shape], /) -> Array[Shape]: ...
@overload
def igammac[Shape1: _Shape, Shape2: _Shape](
    a: Array[Shape1], x: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def le[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def le[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def le[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def lt[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def lt[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def lt[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def max[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def max[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def max[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def min[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def min[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def min[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def mul[Shape: _Shape](
    x: Array[Shape],
    y: _Scalar,
    /,
    *,
    out_dtype: Any = None,
) -> Array[Shape]: ...
@overload
def mul[Shape: _Shape](
    x: _Scalar,
    y: Array[Shape],
    /,
    *,
    out_dtype: Any = None,
) -> Array[Shape]: ...
@overload
def mul[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1],
    y: Array[Shape2],
    /,
    *,
    out_dtype: Any = None,
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def mulhi[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def mulhi[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def mulhi[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def ne[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def ne[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def ne[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def nextafter[Shape: _Shape](x1: Array[Shape], x2: _Scalar, /) -> Array[Shape]: ...
@overload
def nextafter[Shape: _Shape](x1: _Scalar, x2: Array[Shape], /) -> Array[Shape]: ...
@overload
def nextafter[Shape1: _Shape, Shape2: _Shape](
    x1: Array[Shape1], x2: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def polygamma[Shape: _Shape](m: Array[Shape], x: _Scalar, /) -> Array[Shape]: ...
@overload
def polygamma[Shape: _Shape](m: _Scalar, x: Array[Shape], /) -> Array[Shape]: ...
@overload
def polygamma[Shape1: _Shape, Shape2: _Shape](
    m: Array[Shape1], x: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def pow[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def pow[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def pow[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def rem[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def rem[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def rem[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def shift_left[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def shift_left[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def shift_left[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def shift_right_arithmetic[Shape: _Shape](
    x: Array[Shape], y: _Scalar, /
) -> Array[Shape]: ...
@overload
def shift_right_arithmetic[Shape: _Shape](
    x: _Scalar, y: Array[Shape], /
) -> Array[Shape]: ...
@overload
def shift_right_arithmetic[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def shift_right_logical[Shape: _Shape](
    x: Array[Shape], y: _Scalar, /
) -> Array[Shape]: ...
@overload
def shift_right_logical[Shape: _Shape](
    x: _Scalar, y: Array[Shape], /
) -> Array[Shape]: ...
@overload
def shift_right_logical[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def sub[Shape: _Shape](x: Array[Shape], y: _Scalar, /) -> Array[Shape]: ...
@overload
def sub[Shape: _Shape](x: _Scalar, y: Array[Shape], /) -> Array[Shape]: ...
@overload
def sub[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], y: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
@overload
def zeta[Shape: _Shape](x: Array[Shape], q: _Scalar, /) -> Array[Shape]: ...
@overload
def zeta[Shape: _Shape](x: _Scalar, q: Array[Shape], /) -> Array[Shape]: ...
@overload
def zeta[Shape1: _Shape, Shape2: _Shape](
    x: Array[Shape1], q: Array[Shape2], /
) -> Array[lax_broadcast(Shape1, Shape2)]: ...
